# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Album Unknown', max_length=255)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('album_rating', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Artist Unknown', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LibraryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_snapshot', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_order', models.IntegerField(blank=True, null=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itl.Playlist')),
            ],
            options={
                'ordering': ['playlist_order'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bit_rate', models.IntegerField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('compilation', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('disc_count', models.IntegerField(blank=True, null=True)),
                ('disc_number', models.IntegerField(blank=True, null=True)),
                ('grouping', models.CharField(blank=True, max_length=255, null=True)),
                ('lastplayed', models.DateTimeField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('loved', models.BooleanField(default=False)),
                ('movement_count', models.IntegerField(blank=True, null=True)),
                ('movement_name', models.CharField(blank=True, max_length=255, null=True)),
                ('movement_number', models.IntegerField(blank=True, null=True)),
                ('persistent_id', models.CharField(blank=True, max_length=255)),
                ('play_count', models.IntegerField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('sample_rate', models.IntegerField(blank=True, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('skip_count', models.IntegerField(blank=True, null=True)),
                ('skip_date', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(default='Unknown', max_length=255)),
                ('total_time', models.IntegerField(blank=True, null=True)),
                ('track_id', models.IntegerField(blank=True, null=True)),
                ('track_number', models.IntegerField(blank=True, null=True)),
                ('track_count', models.IntegerField(blank=True, null=True)),
                ('work', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itl.Album')),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itl.Artist')),
                ('composer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='track_composer', to='itl.Artist')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itl.Genre')),
                ('kind', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itl.Kind')),
            ],
        ),
        migrations.CreateModel(
            name='TrackType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='track',
            name='track_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='track_type', to='itl.TrackType'),
        ),
        migrations.AddField(
            model_name='playlistentry',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itl.Track'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['name'], name='itl_artist_name_323d91_idx'),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itl.Artist'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['comments', 'persistent_id', 'title'], name='itl_track_comment_a2cd17_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['title'], name='itl_album_title_232950_idx'),
        ),
    ]
