# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_loved',
            field=models.BooleanField(default=False),
        ),
    ]
