# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='loved',
            field=models.BooleanField(default=False),
        ),
    ]
