# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itl', '0003_auto_20170513_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='location',
        ),
        migrations.RemoveField(
            model_name='track',
            name='location_escaped',
        ),
    ]
