# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itl', '0003_auto_20170529_0655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='librarydata',
            options={'verbose_name_plural': 'Library Metadata'},
        ),
        migrations.RemoveField(
            model_name='track',
            name='year',
        ),
        migrations.AddIndex(
            model_name='year',
            index=models.Index(fields=['year'], name='itl_year_year_2f8068_idx'),
        ),
    ]
