# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itl', '0003_track_persistent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='album_artist',
        ),
    ]
