# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itl', '0005_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itl.Playlist'),
        ),
    ]
