# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itl', '0005_auto_20170519_0620'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_snapshot', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='track',
            name='playlists',
        ),
    ]
