# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itl', '0006_auto_20170520_0840'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='track',
            name='itl_track_persist_7fe3a9_idx',
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['comments', 'persistent_id', 'title'], name='itl_track_comment_a2cd17_idx'),
        ),
    ]
