# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 06:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itl', '0006_track_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='playlist',
        ),
    ]
