# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itl', '0007_remove_track_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='playlists',
            field=models.ManyToManyField(blank=True, null=True, to='itl.Playlist'),
        ),
    ]
