# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itl', '0007_auto_20170521_0604'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['title'], name='itl_album_title_232950_idx'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['name'], name='itl_artist_name_323d91_idx'),
        ),
    ]
