# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itl', '0009_auto_20170505_0633'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['persistent_id'], name='itl_track_persist_7fe3a9_idx'),
        ),
    ]
